#!/usr/bin/env python3
"""
Generate runtime/manifest.md: a snapshot of installed packages,
DuckDB extensions, and toolkit helpers. The AI reads this via MCP.

Run manually:
    python mcp/manifest_generator.py

Or let setup.py run it automatically at the end.
"""

from __future__ import annotations

import json
import platform
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent.resolve()
RUNTIME = ROOT / "runtime"
MANIFEST = RUNTIME / "manifest.md"
OS = platform.system().lower()


def python_exe() -> Path:
    """Return the portable Python executable path."""
    if OS == "windows":
        return RUNTIME / "python" / "python.exe"
    return RUNTIME / "python" / "bin" / "python3"


def pip_list() -> list[dict]:
    """Return list of installed packages with versions."""
    py = python_exe()
    if not py.exists():
        return []
    r = subprocess.run([str(py), "-m", "pip", "list", "--format=json"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return []
    try:
        return json.loads(r.stdout)
    except Exception:
        return []


def duckdb_version() -> str:
    py = python_exe()
    if not py.exists():
        return "not installed"
    r = subprocess.run([str(py), "-c", "import duckdb; print(duckdb.__version__)"],
                       capture_output=True, text=True)
    return (r.stdout.strip() or r.stderr.strip()) if r.returncode == 0 else "error"


def duckdb_extensions() -> list[dict]:
    """Return list of installed DuckDB extensions."""
    py = python_exe()
    if not py.exists():
        return []
    ext_dir = RUNTIME / "duckdb" / "extensions"
    code = (
        "import duckdb, json;"
        "con = duckdb.connect();"
        f"con.execute(\"SET extension_directory='{ext_dir}'\");"
        "rows = con.execute("
        "'SELECT extension_name, installed, description "
        "FROM duckdb_extensions() WHERE installed ORDER BY extension_name'"
        ").fetchall();"
        "print(json.dumps([{'name': r[0], 'description': r[2]} for r in rows]))"
    )
    r = subprocess.run([str(py), "-c", code], capture_output=True, text=True)
    if r.returncode != 0:
        return []
    try:
        return json.loads(r.stdout)
    except Exception:
        return []


def toolkit_modules() -> list[str]:
    """List available toolkit helper modules."""
    tk = ROOT / "toolkit"
    if not tk.exists():
        return []
    return sorted(p.stem for p in tk.glob("*.py") if p.stem != "__init__")


def build_manifest() -> str:
    lines = []
    lines.append("# Environment Manifest")
    lines.append("")
    lines.append(f"Generated: {datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"OS: {platform.system()} {platform.release()}")
    lines.append(f"Architecture: {platform.machine()}")
    lines.append("")

    # Python packages
    lines.append("## Python packages")
    lines.append("")
    pkgs = pip_list()
    if pkgs:
        lines.append("| Package | Version |")
        lines.append("|---|---|")
        for p in sorted(pkgs, key=lambda x: x["name"].lower()):
            lines.append(f"| `{p['name']}` | {p['version']} |")
    else:
        lines.append("_No packages found._")
    lines.append("")

    # DuckDB
    lines.append("## DuckDB")
    lines.append("")
    lines.append(f"- Version: **{duckdb_version()}**")
    lines.append("")

    # Extensions
    lines.append("## DuckDB extensions")
    lines.append("")
    exts = duckdb_extensions()
    if exts:
        lines.append("| Extension | Description |")
        lines.append("|---|---|")
        for e in exts:
            desc = (e.get("description") or "").replace("\n", " ").strip()
            lines.append(f"| `{e['name']}` | {desc[:120]} |")
    else:
        lines.append("_No extensions installed._")
    lines.append("")

    # Toolkit modules
    lines.append("## Toolkit helper modules")
    lines.append("")
    mods = toolkit_modules()
    if mods:
        for m in mods:
            lines.append(f"- `toolkit.{m}`")
    else:
        lines.append("_No toolkit modules found._")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_This file is auto-generated by `mcp/manifest_generator.py`._")
    lines.append("_Re-run after installing new packages or extensions._")

    return "\n".join(lines)


def main():
    RUNTIME.mkdir(parents=True, exist_ok=True)
    content = build_manifest()
    MANIFEST.write_text(content, encoding="utf-8")
    print(f"Wrote {MANIFEST.relative_to(ROOT)}")
    print(f"  {len(content.splitlines())} lines")


if __name__ == "__main__":
    main()